.TH 保存サイト 1 hozonsite\-VERSION
.SH ソフト名
保存サイト - 世界初FOSS系ウエブアーカイバー
.SH 概要
.B hozonsite
[\fI\,オプション\/\fR] [\fI\,ポート番号\/\fR]
.SH 説明
.PP
保存サイトは世界初FOSS系ウエブアーカイバーです。
.TP
\fB\-v\fR
バージョンを表示
.TP
\fB\-s [ポート番号]\fR
ポート番号でサーバーを開始（デフォルト＝9920）
.TP
\fB\-h\fR
ヘルプを表示
.TP
.B オプションなし
ローカルにウェブページを保存
.SH 会話
.PP
XMPP: xmpp:hozonsite@chat.xmpp.076.ne.jp?join
.br
IRC: irc.076.ne.jp/6697 #hozonsite
.br
メーリングリスト: （開発中）
.SH バグ報告
.PP
バグは下記のURLまでご報告下さい：
.br
https://gitler.moe/suwako/hozonsite/issues
